### ISSUE TITLE
MSPA: Create map scaffolding

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1057]
Part of the Map Single Page App epic (#1031)

# Tasks
- [x] Implement a view e.g. ProjectMap and a template that serves the map. 
    - The template should include: 
       - [x] the map itself
       - [x] the right-hand side panel the display record details.
- [x] Write CSS including transitions to show/hide the panel by changing its CSS class.
- [x] Upgrade to Leaflet 1.0+

**Comment by oliverroick** [comment]
@linzjax I think we can close this?!

**Comment by linzjax** [comment]
Sure!! Clean up abounds, but the spirit of this PR is completed
