### ISSUE TITLE
SMAP: Enable GeoJSON vector tiles

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1058]
Part of the Map Single Page App epic (#1031)

# Tasks
- [x] Enable GeoJSON vector tiles
    - [x] Change spatial.asyc.SpatialUnitList so it can serve GeoJSON vector tiles. 
    - [x] The view supports the [XYZ tile convention](http://wiki.openstreetmap.org/wiki/Slippy_map_tilenames).
    - [x] Change loading of features on the client-side to support GeoJSON vector tiles. 
        - (look at  [TileLayer.GeoJSON](https://github.com/glenrobertson/leaflet-tilelayer-geojson/))

**Comment by linzjax** [comment]
For my own reference:
[Beginning of an vector tile boundary box](https://cadasta.slack.com/files/oliverroick/F3RUZ9G07/async.py)
[url config](https://gist.github.com/oliverroick/31037b1df23e3542bbb1c0afaa8702e4)
