### ISSUE TITLE
SMAP: Update existing views and templates

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1059]
Part of the Map Single Page App epic (#1031)

# Tasks
- [x] Existing views and templates updated so they can be served asynchronously. 
- [x] Both the URLs and view classes moved to the async component the corresponding Django app.
- [ ] Scaffolding removed from the HTML template, and only the contents of the right-hand side panel are rendered.

### Affected views

- [x] `organization.views.default.ProjectDashboard`
- [x] `spatial.views.default.LocationsList`
- [ ] `spatial.views.default.LocationAdd`
- [x] `spatial.views.default.LocationDetail`
- [ ] `spatial.views.default.LocationEdit`
- [ ] `spatial.views.default.LocationDelete`
- [x] `spatial.views.default.LocationResourceAdd`
- [x] `spatial.views.default.LocationResourceNew`
- [x] `spatial.views.default.TenureRelationshipAdd`
- [x] `party.views.default.PartyRelationshipDetail`
- [x] `party.views.default.PartyRelationshipEdit`
- [x] `party.views.default.PartyRelationshipDelete`
- [x] `party.views.default.PartyRelationshipResourceNew`
- [x] `party.views.default.PartyRelationshipResourceAdd`
