### ISSUE TITLE
SMAP: Implement minimal routing and async loading

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1060]
Part of the Map Single Page App epic (#1031)

# Task
- [x] The URL displayed in the address bar is in sync with the current view.
- [x] The view is updated according to the URL when users access the page via a permalink. 
    - (Possibly of help: [A JavaScript router in 20 lines](http://joakim.beng.se/blog/posts/a-javascript-router-in-20-lines.html))
- [x] Implement async loading into the client-side. 
    - [x] Design and implement a framework to handle information flows uni directional. 
    - [x] Changes to the UI only happen when the URL in the browser changes.
    - [x] URL in the browser changes and triggers an event, which will load the resource from the backend and display some loading info to the user.
    - [x] Upon receiving the response, the loading info is removed, and the contents are displayed in the panel. 
    - [x] Track the app's current state in one central variable and update only the state when the user interacts with the platform.
    - [x] Add listeners that track changes to the state and update the UI according to the current state.

**Comment by linzjax** [comment]
## Follow-up Tasks
- [ ] Update Search to work with hash changing.

**Comment by oliverroick** [comment]
Let's be honest; we'll never dig this up from the graveyard of unfinished work. Closing.
