### ISSUE TITLE
SMAP: Store the map position

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1061]
Part of the Map Single Page App epic (#1031)

# Task
Store the map position either in the browser session and/or the URL so it can be recovered through a permalink.

---
### Open a new tab and paste in the URL.
Does the URL have `/?coords=`?
__Yes:__
1. Zoom to coordinate location.

__No:__
1. Check if there is a zoom to function: project_extent, location_bounds
2. Zoom to this specific requirement
3. Then add coordinates to URL.

### If the hash changes:
Was it just the coordinates changing?
__Yes:__
Ignore and move on with your life.

__No:__
Are there ?coords= in the URL still?
Yes => 
1. Ignore them? *THIS ONE I'M NOT SURE ABOUT. If a user presses the back button, where do they go?

No =>
1. Check if there is a zoom to function: project_extent, location_bounds
2. Zoom to this specific requirement
3. Then add coordinates to URL.

---

## When should we...

1. Zoom to Location

- [x] When a location (detail/edit/delete) w/out coordinates is reached through the URL
      - Doesn't work if outside project_extent
- [x] When a relationship (detail/edit) w/out coordinates is reached through the URL
      - Doesn't work if outside project_extent

2. Not Zoom to Location

- [x] When submitting a form
      - Currently, if you submit a form, it loads either location_detail or relationship_detail anew, which zooms in on the location again.
- [x] When switching from a location to a relationships

3. Zoom to Coordinates

- [x] When an overview is reached with coordinates attached.
- [x] When a map is reached with coordinates attached.
      - Because we have to resize the map, the coordinates call gets overridden, and this.lastHash is updated before update is called...
- [x] When a location is reached with coordinates attached.
- [x] When a relationship is reached with coordinates attached.

4. Zoom to project_extent

- [x] When / is reached without coordinates
- [x] When /#/overview is reached w/out coordinates
- [x] When /#/map is reached without coordinates through a new tab [FIRST TIME ONLY]

---

## Current problems with location saving URL

- [x] From the `location_detail` page, actions such as editing and adding a resource remove coords and zoom back in on the location. This should not happen
- [x] When loading a location with coordinates from a new tab via a url, the location geometry is not styled unless the router is called again.
- [x] On `/#/?coords=<blah>` the page snaps back to project_extent when you try to move away
- [x] When clicking a link to a `location_detail` page, the coordinates should not be added until `updateCurrentLocation()` has finished
- [x] When reaching the project through `/#/map` there's no zoom to `project_extent`. 
- [x] If geometry isn't located in view of the`project_extent`, it's styling isn't applied.
- [x] Why is `setLocationStyle()` being called at every map movement?
- [x] When panning around the map there are occasional glitches that snap the map back

**Comment by linzjax** [comment]
What's the expected use case of this? Is it for a single user switching back and forth between pages who needs to quickly return to their last map location? Is it someone who wants to share the project but have a specific subsection of it displayed initially? If I'm sharing a project at a specific map location, would I expect to have to manually 'save and share' the position, or would the URL be auto-populated for me?

**Comment by wonderchook** [comment]
@linzjax I would expect it to be auto-generated for me. I currently use this on other sites to both share a location and also to save one for myself.

**Comment by oliverroick** [comment]
@linzjax What I had in mind was that the map location is part of the URL so that you can copy and share or save it. So whenever you pan or zoom the map the URL should be updated.

**Comment by linzjax** [comment]
Ok, that makes sense. Would you want to be able to do this for every view (overview, location detail, relationship detail, etc.)?

**Comment by wonderchook** [comment]
Yes, I think every view. People will want to be able to send links to each other and end up the same view of the data.

**Comment by linzjax** [comment]
Per conversation on #smap slack, I'm going to use the following URL pattern:
`/organizations/<org-slug>/projects/<proj-slug>/#/<current_router_location>/?coords=<zoom>/<lat>/<lng>/`

**Comment by linzjax** [comment]
## Order of operations:
### Open a new tab and paste in the URL.
Does the URL have `/?coords=`?
__Yes:__
1. Zoom to coordinate location.

__No:__
1. Check if there is a zoom to function: project_extent, location_bounds
2. Zoom to this specific requirement
3. Then add coordinates to URL.

### If the hash changes:
Was it just the coordinates changing?
__Yes:__
Ignore and move on with your life.

__No:__
Are there ?coords= in the URL still?
Yes => 
1. Ignore them? *THIS ONE I'M NOT SURE ABOUT. If a user presses the back button, where do they go?

No =>
1. Check if there is a zoom to function: project_extent, location_bounds
2. Zoom to this specific requirement
3. Then add coordinates to URL.

---

## When should we...

1. Zoom to Location

- [ ] When a new location is access through a pop-up
- [ ] When a location w/out coordinates is reached through the URL
      - Doesn't work if outside project_extent
- [ ] When a relationship w/out coordinates is reached through the URL
      - Doesn't work if outside project_extent

2. Not Zoom to Location

- [ ] When submitting a form
      - Currently, if you submit a form, it loads either location_detail or relationship_detail anew, which zooms in on the location again.
- [ ] When switching from a location to a relationships

3. Zoom to Coordinates

- [ ] When an overview is reached with coordinates attached.
- [ ] When a map is reached with coordinates attached.
      - Because we have to resize the map, the coordinates call gets overridden, and this.lastHash is updated before update is called...
- [ ] When a location is reached with coordinates attached.
- [ ] When a relationship is reached with coordinates attached.

4. Zoom to project_extent

- [ ] When / is reached without coordinates
- [ ] When /#/overview is reached w/out coordinates
- [ ] When /#/overview tab is clicked after panning around the screen.
- [ ] When /#/map is reached without coordinates through a new tab [FIRST TIME ONLY]

---

## Current problems with location saving URL

- [ ] From the location_detail page, actions such as editing and adding a resource remove coords and zoom back in on the location. This should not happen
- [ ] When loading a location with coordinates from a new tab via a url, the location geometry is not styled unless the router is called again.
- [ ] On /#/?coords=<blah> the page snaps back to project_extent when you try to move away
- [ ] If /#/overview had coords, and now doesn't, it should snap back to project_extent
- [ ] When clicking a link to a location_detail page, the coordinates should not be added until updateCurrentLocation() has finished
- [ ] When reaching the project through /#/map there's no zoom to project_extent. 
- [ ] If geometry isn't located in view of the project_extent, it's styling isn't applied.
- [ ] Why is setLocationStyle() being called at every map movement?
