### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#130]
# Summary
Resources are documentation that are uploaded to Cadasta and associated to entities. This task is to create the resources workflow

# Links to requirements and functional testing script
* [Requirements](https://github.com/Cadasta/cadasta-platform/wiki/2.3-Project-Resources)

# Acceptance criteria
* User can upload files
* Resources are saved to S3
* User can associate resources to entities
* API is documented

# Task list (including tests)
- [x] Implement Django model for Resource

## Resource API Design

- [x] Resource list with search, filter, sort (resource API Design)
- [x] Access resource details (resource API Design)
- [x] Create, update (resource API Design)
- [x] Archive/unarchive (resource API Design)

## Resource API Views
- [x]  Create
- [x]  Update
- [x]  List (with search, filter, sort)
- [x]  Detail view
- [x]  Summary view
- [x]  Archive/unarchive
- [ ]  Assignment to Parcel, Relationship or Party

## Resource API Tests

- [x] TEST Each view for: Successful requests; Unauthenticated requests; Unauthorized requests; Invalid payloads.

## Resource Templates
- [x]  Create
- [x]  Update
- [x]  List (with search, filter, sort)
- [x]  Detail view
- [ ]  Summary view
- [x]  Archive/unarchive
- [ ]  Assignment to Parcel, Relationship or Party

## Other Resource Tasks

- [ ] Create procedure for assigning resource permissions
- [x] DRF serializer for resources
- [ ] Resource Management UI
- [ ] Document Resource API

**Comment by eomwandho** [comment]
1. How is the summary view different from list view? Under task sub-heading "Resource API views"

2. Since we don't have apps or implementations of Parcel, Relationship or Party, should I implement test apps for those entities to work with?

**Comment by wonderchook** [comment]
1. The summary view might not be necessary. 
2. You shouldn't need to implement test apps, I would just stub this until those are implemented.

**Comment by eomwandho** [comment]
When adding a resource from the library, is the assumption true that the library includes only those resources that belong to that entity? or all entities within an organization?

Two scenarios could arise:

If the library refers to a single entity resource library, then a user wants to add a resource to that entity, it would render entity library unusable, since only those resources within that entity will be listed.

On the other hand of library refers to all resources that belong to organization entities, then it would make sense, since if a resource does not belong to one entity, but exist within another entity, then it could be added to that referring entity.

Also would it be possible to have a resource that doesn't belong to any entities? And resource that belongs to more than one entity?
