### ISSUE TITLE
Entity Attributes Data Model Part 1

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#131]
# Summary

*This issue covers only the initial setup of the `django-jsonattrs` module.  See #255 for the rest.*

Adapt existing or implement new Django application for dynamic attribute management

# Links to requirements and functional testing script

[Requirements](https://github.com/Cadasta/cadasta-platform/wiki/Platform-data-model#213-entity-attributes)

# Acceptance criteria

* Entity Attributes Data Model exists
* 100% Test Coverage
* Tests Pass
* *Property Documented* [NOT DONE]
* *Reviewed by Oliver* [NOT DONE] 

# Task list (including tests)

- [x] Review existing Django "dynamic model" packages
- [x] Initial design
- [x] Set up new `django-jsonattrs` project
- [x] **Tests**: fixtures
- [x] **Example app**: basic models, forms, views
- [x] Schema and schema selector models
- [x] **Tests**: schema and schema selector models
- [x] **Example app**: schema management
- [x] Field definition model
- [x] **Tests**: field definition model
- [x] **Example app**: field management
- [x] JSON attributes field class
- [x] Utility functions: get schema from field, get attributes from field
- [x] **Tests**: more fixtures (schema definitions)
- [x] **Tests**: utility functions
- [x] **Example app**: schema view from domain entities
- [x] **Tests**: JSON attributes field class
- [x] Form generation
- [x] **Tests**: form generation
- [x] **Example app**: form generation
- [x] Form validation
- [x] **Test**: form validation
- [x] **Example app**: form validation

**Comment by ian-ross** [comment]
There's probably more to be done on form validation here as well, but it roughly works.  I'll do more on this when I come to incorporate attributes display and management into the platform code.

**Comment by ian-ross** [comment]
This gets the entity attribute modelling into a state where @bjohare can do the attribute schema setup and where I can start incorporating attributes into the front end (see #255).
