### ISSUE TITLE
Asynchronous Exports

### ISSUE THREAD

**Issue by alukach** [Cadasta/cadasta-platform#1400]
Based on [DR 0006: Asynchronous Import and Export](https://github.com/Cadasta/decision-records/blob/master/0006_asynchronous_import_and_export.md), this task is focused on refactoring the data export tooling to support asynchronous operations. 

Asynchronous tasks should be scheduled by placing messages into a queue (most likely hosted via SQS). Celery seems like a reasonable tool to enable this. All data exchange between the Cadasta Platform and async services should go through the Cadasta API. By building services against our API, it will put the API into the place of a first-class feature of our system and ensure that it is battle-tested. It would be beneficial to work any issues out of an API as soon as possible, as alterations to APIs become very difficult once third-parties began building tooling against the API.

## Goals 

Data imports / exports should:

1. Avoid tying-up web server resources with unreasonably large requests
1. Avoid request timeout failures for long data operations
1. Allow users to navigate away from Upload/Export views while data operations continue
Flows

## Tasks

- [x] Convert API list views to utilize pagination
  - **This is a breaking change. Any current API consumers will needed to be updated to work with pagination. [See @SteadyCadence and QGIS Plugin].**
  - _see #1425_
- [x] Implement custom limited-access token authentication
  - See [prototype](https://gist.github.com/alukach/a136b5c07d1b9d2bd8b36173ec53f656/)
  - _see [Cadasta/drf-tmp-scoped-token](/Cadasta/drf-tmp-scoped-token)_
- [x] Create model to store BackgroundJob
  - This includes CRUD API Endpoints for BackgroundJob model
  - Model should be compatible with Celery Result Backend
  - _see #1624_
- [x] Integrate Celery Result Backend to utilize BackgroundJob Model
  - Lots of ways to implement this, we may be able to use RPC backend or write our own (see celery/celery#1581)
  - _see #1624_
- [x] Abstract Celery configuration
  - _see [Cadasta/cadasta-workertoolbox](/Cadasta/cadasta-workertoolbox)_
- [x] Implement Circuit Breaker tooling for celery tooling in Cadasta Platform
  - _see celery/kombu#769_
  - _see #1830_
- [x] Break out Export tooling into separate worker. 
  - Worker should authenticate with the API via the temporary limited-access auth token
  - Worker should take advantage of custom Celery Result Backend
  - _see [Cadasta/cadasta-export-worker](/Cadasta/cadasta-export-worker)_
    - [x] Support XLS exports
    - [x] Support Resource bundling
    - [x] Support Shapefile exports
  - [x] Set up logging with OpBeat
- [x] Store related `content_type` and `content_object` on `BackgroundTask` models.
  - _Implementation idea:_ Encode this data as task metadata when scheduled from Cadasta Platform. `sync_task` process will then use that metadata to populate fields.
- [x] ~Create email worker to send task outcomes to users.~
  - ~_see [Cadasta/cadasta-msg-worker](/Cadasta/cadasta-msg-worker)_~
  - _Email notifications will not be completed in this feature. Users can check export statuses via the Project Dashboard._
- [x] Create zip management server
  - _see [Cadasta/ZipStream-Service](/Cadasta/ZipStream-Service)_

**Comment by alukach** [comment]
# Dev Notes

### Changes to download package

* `locations.xls` generated during shp download now contains `geometry.ewkt` column (it was simpler to leave this in, it could be removed if need be)
* `resources.xls` now contains `filename` column to describe their filename in the zip. This can differ from `original_name` as a number is appended to the filename if it conflicts with a filename in the zip (ie `['foo.jpg', 'foo.jpg']` -> `['foo.jpg', 'foo_2.jpg']`)
* zip filename template changed from `{project.id}-{user.id}-{unixtime}-{datatype}.zip` to `{date.isoformat}_{organization.slug}_{project_slug}_{datatype}.zip` where `datatype` is one of `['res', 'shp', 'xls', 'all']`.
* `README.txt` no longer supports internationalization. Additionally, it does not include the Project Name.
* I opted not to create `.csv` files when exporting Shapefiles. These files contained the same data as the `.xlsx` files. Instead, Shapefile exports now imply an XLS export process.

### Minimum permissions needed for worker DB users

```sql
CREATE USER asyncworker WITH PASSWORD 'password';
GRANT SELECT, INSERT, UPDATE ON celery_taskmeta TO asyncworker;
GRANT USAGE ON task_id_sequence TO asyncworker ;
```

### Ensuring DB is accessible outside of Vagrant machine

I've set my Postgres config to the following (I can't recall if these needed to be changed or were already like this)

#### `/etc/postgresql/9.4/main/pg_hba.conf`

```conf
# Database administrative login by Unix domain socket
local   all             postgres                                peer

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```

#### `/etc/postgresql/9.4/main/postgresql.conf`
```conf
# ...
listen_addresses = '*'
```

#### `Vagrantfile`
```
  # ...
  config.vm.network "forwarded_port", guest: 5432, host: 5433
  # ...
```

### Running the worker

I've been running this from my machine (not the Vagrant box)

```sh
S3_BUCKET=cadasta-test-async-downloads RESULT_DB_USER=asyncworker RESULT_DB_PASS=password RESULT_DB_PORT=5433 ./startworker -l INFO
```

**Comment by alukach** [comment]
Dev TODOs:

* Document the usage of `is_result` when scheduling tasks.

**Comment by seav** [comment]
Looking at the list of tasks, I don't see the task to convert the Search Export tooling into an async task, similar to the regular project download task.

**Comment by alukach** [comment]
@seav That's a good TODO, however I believe that is out of the scope of this feature (see [this comment](https://github.com/Cadasta/cadasta-platform/issues/1464#issuecomment-299378712) for more thoughts on the subject). This feature is limited to just supporting the current Shapefile/Resources/XLS export functionality. Naturally, this includes building out the framework to support asynchronous tasks.  Considering that it's taken over 4 months for us to achieve this, I think we should not consider expanding the scope at all and tie this off ASAP. I've made #1829 to hold a place for this, it will be at the discretion of the product owner to prioritize the feature.

**Comment by seav** [comment]
> I believe that [search exports] is out of the scope of this feature

@alukach: Agreed. And thanks for creating the new issue so that we can track this.
