### ISSUE TITLE
Field Papers - Integration with Cadasta

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1445]
Updated format: 

### Problem Statement 

Field Papers is a tool to help you create a multi-page atlas, manually define the geometries within it, and then collect information scanning these atlases. 

### Context / Use Case

Being able to support Field Papers would provide a good differentiator for Cadasta, as will be offering a possibility to work with paper maps to partners that are working with paper when on the field and are using these maps to validate the data with communities. 

### User Stories

- [ ] US1: As a data collector I want to print atlas of various sizes (what Field Papers currently supports: letter, A3, A4)
- [ ] US2: As a data collector I want to create an atlas automatically of my entire project area
- [ ] US3: As a data collector I want to create an atlas of a specific area I select from a map 
- [ ] US4: As a data collector I want to print maps with 1/2 the page blank to take notes
- [ ] US5: As a data collector I want to after writing on my map, to take a picture of my map and upload it 
- [ ] US6: As a data collector I want to after uploading my map, to use it as a background layer within my project to to digitize 
- [ ] US7: As a data collector I want to upload the same map multiple times and have each one be saved as a separate resource 
- [ ] US8: As a data collector I want to print atlases with different basemaps including custom ones 
- [ ] US9: As a data collector I want to select my map orientation to choose between landscape and portrait 
- [ ] US10: As a data collector I want to associate my map with the entire project or with a specific location 

### Description 

Related Tasks #567 #568 #569 

Link to the information in the wiki [here](https://devwiki.corp.cadasta.org/Field%20Papers%20Integration)

----
Integrate Field Papers tools with Cadasta

Related Tasks #567 #568 #569 

Link to the information in the wiki [here](https://devwiki.corp.cadasta.org/Field%20Papers%20Integration)

## Summary

As a data collector, I want to 

## User Stories

- [ ] US1: As a data collector I want to print atlas of various sizes (what Field Papers currently supports: letter, A3, A4)
- [ ] US2: As a data collector I want to create an atlas automatically of my entire project area
- [ ] US3: As a data collector I want to create an atlas of a specific area I select from a map 
- [ ] US4: As a data collector I want to print maps with 1/2 the page blank to take notes
- [ ] US5: As a data collector I want to after writing on my map, to take a picture of my map and upload it 
- [ ] US6: As a data collector I want to after uploading my map, to use it as a background layer within my project to to digitize 
- [ ] US7: As a data collector I want to upload the same map multiple times and have each one be saved as a separate resource 
- [ ] US8: As a data collector I want to print atlases with different basemaps including custom ones 
- [ ] US9: As a data collector I want to select my map orientation to choose between landscape and portrait 
- [ ] US10: As a data collector I want to associate my map with the entire project or with a specific location

**Comment by dpalomino** [comment]
Description updated with links to requirements and list of user stories.

**Comment by dpalomino** [comment]
Updated format: 

### Problem Statement 

Field Papers is a tool to help you create a multi-page atlas, manually define the geometries within it, and then collect information scanning these atlases. 

### Context / Use Case

Being able to support Field Papers would provide a good differentiator for Cadasta, as will be offering a possibility to work with paper maps to partners that are working with paper when on the field and are using these maps to validate the data with communities. 

### User Stories

- [ ] US1: As a data collector I want to print atlas of various sizes (what Field Papers currently supports: letter, A3, A4)
- [ ] US2: As a data collector I want to create an atlas automatically of my entire project area
- [ ] US3: As a data collector I want to create an atlas of a specific area I select from a map 
- [ ] US4: As a data collector I want to print maps with 1/2 the page blank to take notes
- [ ] US5: As a data collector I want to after writing on my map, to take a picture of my map and upload it 
- [ ] US6: As a data collector I want to after uploading my map, to use it as a background layer within my project to to digitize 
- [ ] US7: As a data collector I want to upload the same map multiple times and have each one be saved as a separate resource 
- [ ] US8: As a data collector I want to print atlases with different basemaps including custom ones 
- [ ] US9: As a data collector I want to select my map orientation to choose between landscape and portrait 
- [ ] US10: As a data collector I want to associate my map with the entire project or with a specific location 

### Description 

Related Tasks #567 #568 #569 

Link to the information in the wiki [here](https://devwiki.corp.cadasta.org/Field%20Papers%20Integration)
