### ISSUE TITLE
Project Dashboard

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#1447]
# Project Dashboard

## Wireframes

- [Download wireframes (Pages 6, 7 and 8)](https://drive.google.com/open?id=0BzpiEtMtHC3rTzREZkY4b3dYSUU)

**Note:** The wireframes currently contain that we won't implement in this first stage (for example; activity feeds, user profile pictures, project cover photos). Focus on the things that we can support now without adding any new features.

## Task breakdown

- [x] About this project
    - [x] Display project description
    - [x] Display project contacts
    - [x] Display project URL
    - [x] Add link to edit project detail page
    - [x] Make sure the link to edit project details is hidden from users who a not project administrators
- [x] Project records
    - [x] Add link to import data
    - [x] Add link to download data
    - [x] Make sure the area is hidden from users that are not project administrators
- [ ] Team members
    - [x] List members of the project. We don't have profile images for users yet, the list will be similar to the one used for organization members on the organization dashboard. The template for the members should be reusable, so this task includes a small refactoring of the organization dashboard template as well. 
    - [x] Add link to edit member permissions
    - [x] Make sure the link to edit the member permissions is hidden from users who a not project administrators
    - [ ] Implement functionality to add a new member to the project (This isn't designed yet, will this be added? Probably should be a separate task because it's a new feature)
    - [x] Make sure functionality to add a new member to the project is hidden from users who a not project administrators
- [x] Project statistics
    - [x] Show the number of locations
    - [x] Show the number of parties
    - [x] Show the number of resources
    - [x] Deleted/archived items are excluded from the stats. 
- [x] Project Map. 
    - [x] Implement state when no project extent is specified. (Show the world map and display link to add a project extent).
    - [x] Implement state when project extent specified but no data is added to the project. (Zoom the map to the project extent.)
    - [x] Implement state when data is added to project (Zoom the map to the project extent; display data).
    - [x] Add link to edit the project map
    - [x] Make sure the link to edit the project map is hidden from users who a not project administrators
- [x] Data Collection
    - [x] Add option to upload a new XLSForm when no form is added to the project. 
    - [x] Add option to replace the current XLSForm when a form was previously added to the project.
    - [x] Block upload of new form when data has been added to the project.
- [x] Project dashboard for non-permissioned users
    - [x] About the project (including description, URL, contacts)
    - [x] Project map (locations on the map should not be clickable)
    - [x] Statistics

"Information that we could include: 
 - Additional stats : we currently have locations, entities, resources. We could also add:
    + last updated timestamp
    + number of records added in the last month (or even an usage graph showing the number of committed records in a timeline)
    + number of public users/project users/data collectors/project managers
    + total covered area (when supporting ""Area of locations"" feature)
 - Links to custom reports (when available)
 - Information regarding additional basemaps (when available)
 - Links to survey forms (when supporting multiple survey forms)

For projects not totally defined (lacking of project extent, data design, etc) this will be highlighted in the project dashboards, as it is described in the Project Creation Wizard wireframes. "

**Comment by clash99** [comment]
Hi @bjohare - Here is where I am on the project overview / dashboard:

**Getting Started** 
- Currently placeholder text for projects without content.  We should leverage some of the project documentation for how to get started. I feel like this is a good replacement for the starter text section I removed. I will reach out to @bethschechter for ideas on what we could use.

**Project Map** 
- What do you think about removing the overlay once a location record has been added? 
Also need to make overview map not clickable.

**Data Collection** 
- Added alert information with links to samples for when no questionnaire has been added.

**Project Details** 
- I'm assuming any real project will have a description at least. Otherwise perhaps we should consider an overlay here that says something like "You can add a description ...". Thoughts?

**Project Records** 
- Should we hide this section until a questionnaire has been uploaded? 
- Should we hide the export option until records have been collected?

**Team Members**
- Until we can get user profile pics, I've added a list of usernames and roles.
- Can we add Administrators to the list of team members?
- Public user's role is being displayed as "Pb". Can we modify to say Public User?

**Request Access**
- Added to right column for registered members that don't belong to a project. If we can't do this now, I'm wondering what I can put here so it is not empty.

**Sign In**
- In right column for unregistered users - seems like we can use this area for messaging of benefits of registering. 
 
**Still in progress:**
- I'm still working on design and css so excuse some of the things looking a bit loud or wonky.
- Need to add hover actions to action icons.
- Still looking at another glyphicon font suite for better icon options.
- Need to add responsive css for this page.
- I need to make sure we are using "export data" consistently (vs. download).
- Making another task to consider adding relevant stats such as up/down percentages for numbers to provide more of a true dashboard.
- Need to tackle organization pages too.

**Comment by clash99** [comment]
@bethschechter - We are in the process of remodeling the project dashboard/overview page and are wondering if you have any documentation that we could repurpose for two places:

**1)  Getting started text for new projects**

![screenshot 2017-05-19 15 01 10](https://cloud.githubusercontent.com/assets/1119621/26264929/49f2e9a6-3ca4-11e7-8281-16f101ac5310.png)

2) **Marketing-type of content for benefits of registering** (would accompany the sign in button here) 

![screenshot 2017-05-19 15 05 34](https://cloud.githubusercontent.com/assets/1119621/26264995/a5bc9bba-3ca4-11e7-92dc-7ff5cfd04f7b.png)

Let me know if you have any ideas. Thanks, Chandra

**Comment by bethschechter** [comment]
@clash99 so the two spots are Getting Started and About This Project?

Do we expect that users will modify the About this Project section?

**Comment by SteadyCadence** [comment]
@bethschechter @clash99 Maybe the "About this Project" could be like a mad lib where you just fill out keywords :) 

Or we could have tags that users choose.  That way we can start to categorize questionnaires and data sets.

**Comment by bethschechter** [comment]
@SteadyCadence @clash99 We could - do we plan to use this section as a way to categorize projects?

**Comment by clash99** [comment]
@SteadyCadence - Categories and tags are listed for the next phase of development.

@bethschechter - We need text for the "Getting Started" block in the first screenshot. Could be text now but future link to video or something... And the other is around the "Sign In" section in the second screenshot. I think this area has a lot of potential for messaging of benefits of registering (marketing).

**Comment by bethschechter** [comment]
aaaaaaah thank you @clash99 that's super helpful context :)

**Comment by bethschechter** [comment]
@clash99 here's some copy for you:
https://docs.google.com/document/d/1rZNhi5_2u7QlDVnYkjX-qQh2tWSA5MWFv4QN9Mfezi0/edit#

There are some notes in the doc about it too. Please let me know if you have questions. I may be able to get online a little next week.

**Comment by bjohare** [comment]
@clash99 I'm not sure what the 'Use Global Map' button on the map overlay actually means in practice. Should we replace this with 'Add Location'?
![global_map](https://cloud.githubusercontent.com/assets/3308136/26303350/50e31514-3edf-11e7-8128-5ea48c5a0d16.png)

**Comment by oliverroick** [comment]
@bjohare _Use Global Map_ is a new feature, so it's out of scope for your current work. We haven't figured out what a global map actually means technically.

**Comment by bjohare** [comment]
@oliverroick ok thanks.

**Comment by clash99** [comment]
@dpalomino - Here are screenshots of org pages for reviewing;

## Organization Dashboard

Org Admin - Member view for organization with projects: 

![screenshot 2017-05-23 15 47 54](https://cloud.githubusercontent.com/assets/1119621/26375608/3b5fe3de-3fcf-11e7-8b79-4cdf9b8b87bb.png)

Org Admin - Member view for organization without projects (starter text): 

![screenshot 2017-05-23 15 43 59](https://cloud.githubusercontent.com/assets/1119621/26375465/b44c81ae-3fce-11e7-893a-c74105b27bcd.png)


## Organization Overview

Non-member view for organization with projects: 

![screenshot 2017-05-23 15 51 18](https://cloud.githubusercontent.com/assets/1119621/26375754/bb72107e-3fcf-11e7-8a8d-33bb26f76dcd.png)


Non-member view for organization with no public projects (slim):
 
![screenshot 2017-05-23 15 52 24](https://cloud.githubusercontent.com/assets/1119621/26375797/e5be5932-3fcf-11e7-813c-15b5427309f6.png)

**Comment by clash99** [comment]
@dpalomino - Here are screenshots of project for reviewing. I'm still working on css (responsive and stats boxes).

## Project Dashboard

Org Admin - View for unfinished project:

![screenshot 2017-05-23 16 09 43](https://cloud.githubusercontent.com/assets/1119621/26376544/7da26d18-3fd2-11e7-9584-8d267e6eff30.png)

Org Admin - View for finished project with no content:

![screenshot 2017-05-23 16 17 28](https://cloud.githubusercontent.com/assets/1119621/26376818/795435f6-3fd3-11e7-806f-e9fc38cf6051.png)


Org Admin - View for finished project with content:

![screenshot 2017-05-23 16 12 55](https://cloud.githubusercontent.com/assets/1119621/26376616/c3462ada-3fd2-11e7-99a3-8a8cb5df60fc.png)

## Project Overview

Unregistered user:

![screenshot 2017-05-23 16 20 03](https://cloud.githubusercontent.com/assets/1119621/26376945/f763e77a-3fd3-11e7-886b-2b95f6b325ca.png)

Non-project member:

![screenshot 2017-05-23 16 21 06](https://cloud.githubusercontent.com/assets/1119621/26376955/03a94f8e-3fd4-11e7-9672-119cf6b9c3b6.png)

**Comment by dpalomino** [comment]
@clash99, it is looking great! I'm reviewing and taking some notes. Maybe we could review together tomorrow?

**Comment by clash99** [comment]
Making an inventory of missing parts while fresh that are tagged for future sprints ([based on these wireframes](https://drive.google.com/open?id=0BzpiEtMtHC3rUGxpb29IMVJwYzA)):

## Organization Dashboard/ Overview
- Organization logo #258 
- Map showing all locations on map #1524
- Team member user profiles #1485 

## Project Dashboard/ Overview
- Improve marketing messages for unregistered members #1069
- Improve help text for new projects #1072, #1525
- Cover photo #1526
- Project logo #1527
- Project categories #1528
- Project tags #1529
- Data collection languages (part of data design)
- Calculated area covered (from Jon Nording)
- Activity log #1531 #1488
- Data design feature
- Add team members at project level #1532
- Adding useful statistics #1550
