### ISSUE TITLE
Records

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#172]
# Summary
Records consists of Location, Relationships and Parties. All three of these items are closely related to each other so they are laid out below. A record must have at least one entry of a location(note: I can’t think of a way you could have a relationship without at least a location or a party). For example some location data might not contain ownership information so it may only contain parcel records in that project. Other project may contain location (showing the geometry of a parcels), relationships (showing the ownership) and the parties (information about the person or organization that owns/has rights to the property)

* Location: geometry of a record, can be a point, line or polygon. Parcels, points of interest, community boundaries, pastoral grazing paths
* Relationships: Links locations to parties or locations to locations. Can be relationships such as tenure.
* Parties: organizations, people or other entities associated with a location.

# Links to requirements and functional testing script
* [Requirements](https://devwiki.corp.cadasta.org/2.3%20Project%20Records)
* Functional Test Script (needs changes to [wireframes](https://github.com/Cadasta/cadasta-platform/issues/168))

# Acceptance criteria
* User can create a new location from the map
* User can create a new relationship and party and associate it with a location
* User can search/sort/filter all locations in a locations view
* User can search/sort/filter all parties in a parties views
* User can search/sort/filter all relationships in a relationship view
* User can delete a single location, relationship and party
* It is not possible for a user to create orphaned relationships that are not associated with a location or party
* User can edit locations, relationships and parties 
* User can edit geometry of locations
* When creating and editing locations the user can see the surrounding parcels

# Task list (including tests)

Spatial unit data modelling and API work split out as #177

- [x] Data modeling (including managers if needed and integrity checks) (except spatial units)
- [x] API design (except spatial units)
- [x] API documentation (except spatial units)
- [x] API Review (except spatial units)
- [x] API Views/Serializers Parties
- [x] TEST Parties API (create, view, update, delete)
- [x] API Views/Serializers Relationships
- [x] TEST Relationship API (create, view, update, delete)
- [x] UI Add new record workflow
- [x] UI Edit view location including deleting
- [x] UI Edit view parties including deleting
- [x] UI Edit views relationship including deleting
