### ISSUE TITLE
Creation of Project Records Attribute Schema

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#235]
# Summary
Currently an XLSForm is uploaded and parsed to store questionnaire information. We want to also create the schema for the records of the project during that parsing. This will allow during the initial release a way for users to have custom attributes in their projects, in the future a full GUI will be designed for this. 

# Links to requirements and functional testing script
- [Requirements](https://devwiki.corp.cadasta.org/XLSForm%20Parsing%20and%20Upload#creation-of-project-attribute-schema)

# Acceptance criteria
* When a form is uploaded a schema matching the names of the attributes in the form
* Attributes in the form are assigned to the appropriate entity (location, relationships and parties) based on the prefix of the name (l_, r_, p_) respectively

# Task list (including tests)
- [ ] parse name and type from XLSForm and match to appropriate record entity
- [ ] check to make sure required attributes are in the form
- [ ] create entity in project record schema with name matching the form and type mapped to Cadasta data type

**Comment by wonderchook** [comment]
@bjohare I've taken an initial stab at the tasks, in you review let me know if you think any are missing.

**Comment by wonderchook** [comment]
@bjohare with the acceptance of your pull request, this is complete?

**Comment by bjohare** [comment]
@wonderchook yes, should be.
