### ISSUE TITLE
Entity Attributes Data Model Part 2

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#255]
# Summary

*This is a follow-on from #131, covering incorporating attributes into the front-end, adding attribute capabilities to the API, and documentation.*

Adapt existing or implement new Django application for dynamic attribute management

# Links to requirements and functional testing script

[Requirements](https://github.com/Cadasta/cadasta-platform/wiki/Platform-data-model#213-entity-attributes)

# Acceptance criteria

* Entity Attributes Data Model exists
* 100% Test Coverage
* Tests Pass
* Property Documented
* Reviewed by Oliver 

# Task list (including tests)

*Incomplete tasks moved to new ticket for later release.*

- [ ] Fix any issues with attribute schema creation based on @bjohare's work
- [ ] Basic attribute editing for organizations _(not in v0.1)_
- [ ] Basic attribute display for organizations _(not in v0.1)_
- [ ] Basic attribute editing for projects _(not in v0.1)_
- [ ] Basic attribute display for projects _(not in v0.1)_
- [x] Basic attribute editing for parties
- [x] Basic attribute display for parties
- [x] Basic attribute editing for spatial units
- [x] Basic attribute display for spatial units
- [x] Basic attribute editing for relationships
- [x] Basic attribute display for relationships
- [ ] DRF serialization
- [ ] **Tests**: DRF serialization
- [ ] Documentation
- [ ] Decide on further work for form display, attribute rendering, validation, etc.

**Comment by oliverroick** [comment]
Opened PR #375 that adds attributes to the UI
