### ISSUE TITLE
Shapefile Export

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#323]
## Summary

We want users to be able to download all data in a project as a shape file. This option should be added to the existing download page. 

## Links 

- [Requirements](https://devwiki.corp.cadasta.org/Data%20Download)

## Acceptance criteria

- The user can select the “SHP” option in the download form. The server returns a ZIP containing a shape file with the projects data along with the parties and relationships.
- The same ZIP is also present in the ZIP that is returned from the “All data” option.

## Questions

- How are we going to handle multiple geometry types in our dataset? SHP only allows one geometry type per file, i.e. we need one for each points, lines, and polygons. 

## Task breakdown

- [x] Create `ShapeFileExporter` class that returns a ZIP containing all necessary files (shp, prj, shx, dbf). 
- [x] Test that all locations are present in the shape file with correct geometries. 
- [x] Test that all relationships and parties are present along with the foreign key relations.
- [x] Add shape file export option `organization.forms.DownloadForm` and hook in `ShapeFileExporter`.
- [x] Test that a shape file is returned from the form when the shape download option is submitted to the form. 
- [x] Add the shape export to the “All data” option.
- [x] Test that the shape file is added to the ZIP return from the “All data” option.
- [x] Add shape file export option to `project_download.html` template.
- [x] Adjust the help text of the “all data” option to contain the SHP. 
- [x] Add README to zip, which explains the contents of the ZIP
- [x] Add GDAL installation to Ansible playbooks

**Comment by seav** [comment]
Closed via #523
