### ISSUE TITLE
Administrator cannot archive organization

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#550]
### Steps to reproduce the error

Create a new Organization
Then try to archive it using the Archive Organization button on the Organization Overview page. 

(using Chrome)

[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

### Actual behavior

[Please describe the outcome of your actions.]

Clicking on the Archive Organization button does nothing.

### Expected behavior

[Please explain what behavior you would have expected instead.]

I expected that the archive button would archive the organization. I also did not expect to see the organization still listed as an organization on the Organizations page.

**Comment by ian-ross** [comment]
The problem here isn't so much that the organization doesn't get archived, it's that we don't currently make any distinction between normal and archived entities in the UI.  So fixing this will involve updating all the views to filter out archived organizations (and the same sort of thing for projects as well, I guess).

**Comment by bethschechter** [comment]
Oh I see. That makes sense; though from a user's perspective it just
appears to be broken. Might be something to consider for a future release.

**Comment by ian-ross** [comment]
@bethschechter I agree 100% that it's broken!  We definitely need to fix this.

**Comment by bethschechter** [comment]
copy that! Thanks Ian

@bethschechter

**Comment by linzjax** [comment]
Questions:
1) Should archiving an organization freeze any possible actions on that organization other than 'unarchiving'?
2) Does archiving an organization cascade to the projects within the organization?

**Comment by clash99** [comment]
Original wireframe showing Active/ Inactive/ All option to right of search box.  I think we should update options to Active (default/ unarchived), Archived, and All.

![screenshot 2016-08-22 12 57 26](https://cloud.githubusercontent.com/assets/1119621/17866400/fd66d73a-686b-11e6-9965-b6a5a7e23572.png)


Also since the permissions have changed to allow beyond sysadmins to view these, we should add an indicator to organization index and organization subheader when viewing a single organization to show that its current status is "archived".

![screenshot 2016-08-22 13 30 05](https://cloud.githubusercontent.com/assets/1119621/17866598/b1684de0-686c-11e6-8137-afe066ebc525.png)


![screenshot 2016-08-22 13 25 32](https://cloud.githubusercontent.com/assets/1119621/17866486/4ccc8a18-686c-11e6-847c-07e1f249af9e.png)

This is leveraging bootstrap labels:
`<span class="label label-danger">Archived</span>`

With some added css for h1 and h4 tags:

`h1.label {font-size: 14px; font-weight: 500; vertical-align: middle;}
h4.label {font-size: 11px; font-weight: 500; vertical-align: middle;}`

(Or something similar)

**Comment by clash99** [comment]
@linzjax 

My thoughts to your questions:

1) Should archiving an organization freeze any possible actions on that organization other than 'unarchiving'?

2) Does archiving an organization cascade to the projects within the organization?

My understanding is yes on both counts.  We should include text in the archive modal to notify the user of the results of their archive actions.   We should include the archive dropdown and archive indicator on the project index and single project subheader as well.

**Comment by wonderchook** [comment]
Yes, an archived project shouldn't be able to be modified except to unarchive it. Archived orgs should cascade down as well.

**Comment by linzjax** [comment]
## Task List
### UI
- [ ] Archiving an organization freezes all actions except unarchiving
- [ ] Labels added to organization dashboards and list views to indicate they're archived.
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Archiving/Unarchving an organization should cascade to all projects within the organization
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Archiving a project freezes all actions except unarchiving (unless the org is archived)
- [ ] Labels added to project dashboards and list views to indicate they're archived.
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Archived organization should not be seen in the organization list
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Archived projects should not be seen in the project list
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Org admins should be able to filter the organization list view to see (Active/Archived/All) 
organizations (only archived orgs they are admins for)
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Org admins should be able to filter the project list view to see (Active/Archived/All) projects (only archived projects they are admins for) __What about project managers?__
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Superuser should be able to filter the organization list view to see (Active/Archived/All)
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Superuser should be able to filter the project list view to see (Active/Archived/All)
- [ ] Test (Unit)
- [ ] Test (Functional)
- [ ] Only unarchived projects display on the dashboard map
- [ ] Test (Unit)
- [ ] Test (Functional)

### API
- [ ] Archiving an organization freezes all actions except unarchiving
- [ ] Test (Unit)
- [ ] Archiving/Unarchiving an organization should cascade to all projects within the organization
- [ ] Test (Unit)
- [ ] Archiving a project freezes all actions except unarchiving (unless the org is archived)
- [ ] Test (Unit)
- [ ] Archived organization should not be seen in the organization list
- [ ] Test (Unit)
- [ ] Archived projects should not be seen in the project list
- [ ] Test (Unit)
- [ ] Org admins should be able to filter the organization list view to see (Active/Archived/All) organizations (only archived orgs they are admins for)
- [ ] Test (Unit)
- [ ] Org admins should be able to filter the project list view to see (Active/Archived/All) projects (only archived projects they are admins for) *What about project managers?*
- [ ] Test (Unit)
- [ ] Superuser should be able to filter the organization list view to see (Active/Archived/All)
- [ ] Test (Unit)
- [ ] Superuser should be able to filter the project list view to see (Active/Archived/All)
- [ ] Test (Unit)

**Comment by clash99** [comment]
Couple of comments:

- I would think when an org or project is archived, they would still be display in the index in the alphabetized order with the "archived" label following the name.  Right now they display at the bottom of the list.

- All the member pages within an org are seeing this error when I try to add or edit:  'User' object has no attribute 'archived'.

**Comment by clash99** [comment]
Added css for "archived" labels in your branch:

![screenshot 2016-09-07 11 19 43](https://cloud.githubusercontent.com/assets/1119621/18320281/ca7aaf9c-74ee-11e6-8516-07abf8c5cefa.png)
![screenshot 2016-09-07 11 20 45](https://cloud.githubusercontent.com/assets/1119621/18320282/ca82f742-74ee-11e6-914b-8c1ee16ad2a0.png)
![screenshot 2016-09-07 11 29 11](https://cloud.githubusercontent.com/assets/1119621/18320289/d0ea5e72-74ee-11e6-959b-58be082c20fb.png)
![screenshot 2016-09-07 11 30 28](https://cloud.githubusercontent.com/assets/1119621/18320291/d0ed23be-74ee-11e6-9509-fe3d7bdc279a.png)

**Comment by wonderchook** [comment]
@linzjax moved to Sprint 9 when you will hit the magical merge button.
