### ISSUE TITLE
Add permission filtering the API

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#685]
For the QGIS plugin we need additional filtering of list views based on permissions.

### Task list

- [ ] `GET /api/v1/organizations?permissions=project.create`
  - [ ] Extend the view to read the permissions attribute
  - [ ] Add queryset filtering based on required permissions
  - [ ] Add view test to test correct filtering
- [ ] `GET /api/v1/projects?permissions=project.download,party.create,spatial.create`
  - [ ] Extend the view to read the permissions attribute
  - [ ] Add queryset filtering based on required permissions
  - [ ] Add view test to test correct filtering

**Comment by wonderchook** [comment]
@oliverroick this is closed but the individual tasks aren't checked off. Is it done?

**Comment by oliverroick** [comment]
@wonderchook Yes, it's done. It was merged via #694
