### ISSUE TITLE
Updating questionnaires via the API

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#686]
We need to be able to create and update questionnaires via the API. 
### Use cases
- Schemas can only be updated/replaced as long as there has no data been collected for the project. After that, the project is locked and you cannot add new questionnaires
- The API should support two QGIS use cases:
  1. The project manager wants to add existing data sets from QGIS layers to the platform. They create a new project; the questionnaire structure is created on client-side and uploaded via the API to the platform. Then the data is uploaded. There should be the option to update the data structure after is has been created and before the first record is uploaded. 
  2. The project manager wants to add QGIS data to an existing project. The QGIS plugin displays the current data structure so the project manager can match attributes from the QGIS attribute tables onto the data structure. The mapping is stored locally with the plugin. The attributes are converted into Cadasta’s structure and uploaded via existing API endpoints.
### Task list
- [x] Implement lock to update the questionnaire after records have been added to the project. 
  - [x] Remove the upload field from project edit details page and place a note instead.
  - [x] Write a test that questionnaire is not updated when the project is blocked and a new questionnaire is POSTed to the view. 
  - [x] Return 400 error if an update is attempted via the API.
  - [x] Write a test that questionnaire is not updated when the project is blocked and a new questionnaire is POSTed to the view.
- [x] Design data structure to describe changes to a questionnaire; the same structure is used to create questionnaires.
- [x] Extend `PUT /project/<slug>/questionnaire/` so questionnaires can be created using changesets
  - [x] Extend the manager to create questionnaires via change sets
  - [x] Test new functionality of the manager
  - [x] Extend the serializer to work out whether a form or a change set was uploaded
  - [x] Test new functionality of the serializer
  - [x] Test that the view handles different payload correctly
- [x] Implement generation of XML form from the questionnaire structure.
  - [x] Add XML renderer for questionnaire serialiser.
  - [x] Test XML renderer
  - [x] Add API endpoint.
  - [x] Add content negotiation to the API endpoint. The API should support XML and JSON for now
  - [x] Test API endpoint.

**Comment by wonderchook** [comment]
@oliverroick is this finished and closable?
