### ISSUE TITLE
Asynchronous loading of geographic features

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#931]
To improve the performance of client-side map rendering, the client should load features gradually and asynchronously. 

This task should be coordinated with #932

## Tasks

- [x] Extend spatial unit API view with [pagination](http://www.django-rest-framework.org/api-guide/pagination/). (We can think about a new “internal” API endpoint that serializes only data of spatial units that we need to render the map.)
- [x] Adapt and add API view unit tests accordingly.
- [ ] Document pagination in the [API docs](https://github.com/Cadasta/api-docs).
- [x] Remove spatial-unit serialization form template contexts and templates in all relevant map views. 
- [x] Adapt default view unit tests accordingly. 
- [x] Implement asynchronous loading on client-side for all related map views.
- [x] Add 'loading' indicator when features are loaded from the map.
