### ISSUE TITLE
Improve performance of Leaflet.Deflate

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#932]
Initial parsing and re-rendering of the map after a zoom event is currently inefficient. 

This task should be coordinated with #931

## Tasks

- [x] Ignore all point feature in Leaflet.Deflate
- [x] When initializing new features, group features into bins according to their `zoomthreshold`.
- [x] After zoom event only process the features affected by the zoom action. 
- [x] Test asynchronous loading of features, adapt `layeradd` as necessary.
