### ISSUE TITLE
Demo user password

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#990]
Anyone using the `demo` account on the demo platform can change its password and/or update the email address associated with the account.

There's no 'real' data on demo, but it does pose an inconvenience to prospective site users if they are unable to access the platform by following our prompts.

We could either:

1. Implement superuser functionality to prevent a user from changing their password or updating their email address, or

2. Script a period check of the demo and return these fields to the proper state if they've been modified.

If there's another use case (field agents, maybe?) to justify the enhancement, I'd say #1 is definitely cleaner. Thoughts?

**Comment by clash99** [comment]
@amplifi I agree with #1 but - how would this work?  Would the user be able to see the profile links and pages?  Should we use some sort of messaging informing the user that the demo account profile information isn't able to be modified?

**Comment by amplifi** [comment]
@clash99 Tough question. I think it's valuable for the demo user to be able to see the Edit Profile link and the profile page, with the fields/buttons greyed out and a message displayed, to get an idea of the full feature set. For a field agent, that wouldn't add value but I don't think it would be detrimental. Depends on whether there are other potential use cases, too.

**Comment by clash99** [comment]
@amplifi I agree - its good to show a demo user the profile options. I'm trying to think of how to do this without making it such a one-off, but maybe that can't be avoided.  

Flow suggestion:
- Don't change anything about the profile forms or links to them
- As demo user submits profile form, not accept any of the changes and provide a message saying something like "Thank you for viewing our profile pages.  We don't allow any profile changes to our demo user account.  If you'd like to sign up for your own account, please register (which would link to log them out and then to registration page."  (that wording is rough I know!)
- I don't think we need to add any additional messaging to the pre-submited forms since I don't think most people will be trying to modify the fields but I could be wrong.  We could always put a message there that changes to the demo user account won't be saved.

Thoughts?

**Comment by ragsagar** [comment]
How about adding a form validation in `ChangePasswordForm` to show an error message like "_Demo user cannot change password._"  after checking if the user is `settings.DEMO_USER_ACCOUNT`.

**Comment by oliverroick** [comment]
I would suggest a lightweight solution. Instead of disabling fields or making them read-only, I would implement the method [`clean`](https://docs.djangoproject.com/en/1.10/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other) in both `accounts.forms.ProfileForm` and `accounts.forms.ChangePasswordForm`. Inside `clean` we can check whether the current environment is `demo.cadasta.org` and if the current user is _demo_ and raise a `ValidationError` exception if both applies. The form will not be saved when an Exception is raised and the error message will the be displayed to the user. (Thanks @ragsagar for the initial idea)

To identify the environment, I would add a `CADASTA_ENV` flag to settings, which is a simple string identifying the environment. We will probably need to change our deployment scripts accordingly as I'm not sure if we currently have variations for different environments. 

Functionality similar to the one described for forms needs to be implemented for API serializers as well.

**Comment by oliverroick** [comment]
The most straightforward solution to solve this issue is to add a column to the user model that indicates whether the password can be changed and to raise exceptions in the form and serialisers accordingly:

## Task breakdown

- [ ] Add new field `change_pw` to `User` model. The field is a `BooleanField`, which defaults to `True`.
- [ ] Extend `ChangePasswordForm` to raise an exception if the user can not change their password.
- [ ] Add necessary tests for `ChangePasswordForm`
- [ ] Create a serialiser that extents djoser's [SetPasswordRetypeSerializer](https://github.com/sunscrapers/djoser/blob/master/djoser/serializers.py#L161), which raises an exception if the user can not change their password.
- [ ] Write necessary tests for the new Serializer.
- [ ] Add the new serialiser to the serialiser configuration in settings ([See docs](https://github.com/sunscrapers/djoser#serializers))

**Comment by seav** [comment]
Should there be a UI that allows superusers (only?) to set and unset this `change_pw` flag on a user? Alternatively, we can add a Django management command like `setuserchangepw <user> <bool>`.

**Comment by oliverroick** [comment]
I think, a UI would be overkill at this point, a command sounds reasonable. @amplifi Is this something you think is useful, for example during deployment?

**Comment by wonderchook** [comment]
agreed on holding off on a UI. If it becomes a need beyond the demo users we can think about it later.
